import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";


const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const fontBangla = localFont({
  src: "./../fonts/mayaboti-normal.ttf"
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <header className="w-11/12 mx-auto py-2">
          <Navbar></Navbar>
        </header>
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-303px)]">
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
